create table categories (
    id integer primary key generated by default as identity,
    name varchar(255) not null,
    description text,
    image varchar(255)
);

create table menus (
    id integer primary key generated by default as identity,
    name varchar(255) not null,
    price numeric not null default 0,
    description text,
    image varchar(255)
);

create table menu_category (
    menu_id integer references menus(id) on update cascade on delete cascade,
    category_id integer references categories(id) on update cascade,
    constraint menu_category_pky primary key (menu_id, category_id)
);

create table ingredients (
    id integer primary key generated by default as identity,
    name varchar(255) not null,
    description varchar(255)
);

create table menu_ingredients (
    menu_id integer references menus(id) on update cascade on delete cascade,
    ingredient_id integer references ingredients(id) on update cascade,
    constraint menu_ingredient_pkey primary key (menu_id, ingredient_id)
);

create table users (
    id integer primary key generated by default as identity,
    uuid varchar(255) not null unique,
    full_name varchar(255),
    email varchar(255) not null unique,
    phone varchar(255) not null unique,
    password varchar(255) not null
);

create table roles (
    id integer primary key generated by default as identity,
    name varchar(255) not null unique
);

create table user_roles (
    user_id integer references users(id) on update cascade on delete cascade,
    role_id integer references roles(id) on update cascade,
    constraint use_role_pkey primary key (user_id, role_id)
);

create table orders (
    id integer primary key generated by default as identity,
    placed_at timestamp not null,
    user_id integer references users(id) on update cascade on delete cascade,
    role_id integer references roles(id) on update cascade
);

create table comments (
    id integer primary key generated by default as identity,
    full_name varchar(255),
    message text not null,
    email varchar(255),
    phone varchar(255),
    placed_at timestamp not null

);


